add_newline = false
command_timeout = 500
format = "[$directory$git_branch$git_status$mise]($style)$character"

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 1
truncate_to_repo = true
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "([$path]($style) )[$read_only]($read_only_style)"

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[mise]
disabled = false
format = '[$symbol]($style) '
symbol = '⬢'
style = "green"
